### ISSUE TITLE
Unable to create ContentItemCreateModel 

### ISSUE THREAD

**Issue by knoxor** [Kentico/content-management-sdk-net#21]
Hi,

I am currently working on the evaluation copy (waiting on enterprise licence) and am looking to migrate content from one KenticCloud instance to another instance (development -> Test). I found your SDK and thought this would be perfect.

I've looked at the examples and have tried to create a ContentItemCreateModel type but am getting an error (the Content Management API also gives the same error)

`            
            ContentManagementClient toClient = new ContentManagementClient(toOptions);

            // Defines the content item to import
            ContentItemCreateModel item = new ContentItemCreateModel()
            {
                Name = "Contact Page",
                Type = ContentTypeIdentifier.ByCodename("contact_page")
                // SitemapLocations = new[] { SitemapNodeIdentifier.ByCodename("") }
            };

            ContentItemModel response = await toClient.CreateContentItemAsync(item);
`

error as follows:

`
An unhandled exception of type 'System.AggregateException' occurred in System.Private.CoreLib.dll: 'One or more errors occurred.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 KenticoCloud.ContentManagement.Exceptions.ContentManagementException : The specified content type does not exist.
   at KenticoCloud.ContentManagement.Modules.HttpClient.ContentManagementHttpClient.<SendAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KenticoCloud.ContentManagement.Modules.ActionInvoker.ActionInvoker.<InvokeMethodAsync>d__6`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KenticoCloud.ContentManagement.ContentManagementClient.<CreateContentItemAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at myApp.Program.<CreateContent>d__1.MoveNext() in C:\__workspace\migration\myApp\Program.cs:line 49
`

My question is, is it possible to create the type objects from the sdk and if so, am I doing this correctly?

thanks in advance

**Comment by huluvu21** [comment]
Hi there!
Currently, the CM API does **NOT** support operations for content types. And it seems that there is no content type with codename _contact_page_ in your project.
You need to create the content type manually in the UI. Or you could wait for a few weeks because the support for content models in being developed right now (taxonomy at this very moment).

**Comment by knoxor** [comment]
Hi,
thanks for the quick response. I guess we'll have to manually create the content types for now but hopefully we can use the SDK if we need to in the future.
