### ISSUE TITLE
Help needed moving content from one KenticoCloud instance to another

### ISSUE THREAD

**Issue by knoxor** [Kentico/content-management-sdk-net#23]
Hi, we are looking to move content between different instances of Kentic Cloud e.g. development -> test

I've been looking at the SDK and think this would be our easiest option. I'm able to connect to each instance but I'm getting errors when trying to upload a content item to the second instance.

I'm not familiar with .NET and would appreciate any help on this. I've followed the examples in the readme section

thanks in advance

`
using System;
// using System.Net.Http;
// using System.Threading;
using System.Threading.Tasks;
using ContentManagementClient = KenticoCloud.ContentManagement.ContentManagementClient;
using ContentManagementOptions = KenticoCloud.ContentManagement.ContentManagementOptions;
using ContentItemCreateModel = KenticoCloud.ContentManagement.Models.Items.ContentItemCreateModel;
using ContentItemModel = KenticoCloud.ContentManagement.Models.Items.ContentItemModel;
using ContentTypeIdentifier = KenticoCloud.ContentManagement.Models.Items.ContentTypeIdentifier;
using ContentItemIdentifier = KenticoCloud.ContentManagement.Models.Items.ContentItemIdentifier;
using SitemapNodeIdentifier = KenticoCloud.ContentManagement.Models.Items.SitemapNodeIdentifier;
using KenticoCloud.ContentManagement.Models;
using System.Reflection;

namespace myApp
{
    class Program
    {
        public static void Main() {
            Program program = new Program();
            program.CreateContent().Wait();
        }

        async Task CreateContent() {

            ContentManagementOptions fromOptions = new ContentManagementOptions {
                ProjectId = "xxxxxxxxxxxxxxxxxxxxx", // kentico base
                ApiKey = "xxxxxxxxxxxxx"
            };

            ContentManagementOptions toOptions = new ContentManagementOptions {
                ProjectId = "xxxxxxxxxxxxx", // kentico sample api
                ApiKey = "xxxxxxxxxxx"
            };

            // Initializes an instance of the ContentManagementClient client
            ContentManagementClient fromClient = new ContentManagementClient(fromOptions);
            ContentManagementClient toClient = new ContentManagementClient(toOptions);

            ListingResponseModel<ContentItemModel> response = await fromClient.ListContentItemsAsync();
            while (true) 
            {
                foreach (ContentItemModel item in response) {

                    Console.WriteLine("SitemapLocations::" + item.SitemapLocations);
                    ContentItemCreateModel newContentItem = new ContentItemCreateModel
                    {
                        Name = item.Name,
                        Type = ContentTypeIdentifier.ByCodename(item.CodeName),
                    };
                    ContentItemModel newItem = await toClient.CreateContentItemAsync(newContentItem);
                    printContentItem(newItem);
                }

                if (!response.HasNextPage()) {
                    break;
                }

                response = await response.GetNextPage();
            }
        }

        void printContentItem(ContentItemModel model) {
            Console.WriteLine("Content item::Type:: " + model.GetType().Name);
            Console.WriteLine("Content item::Codename " + model.CodeName);
            Console.WriteLine("Content item::Name " + model.Name);
            Console.WriteLine("Content item::Id " + model.Id);
            Console.WriteLine("Content item::Sitemaplocations " + model.SitemapLocations);
        }
    }
}
`

**Comment by knoxor** [comment]
I've included the error below, it looks like error occurs on line 53
ContentItemModel newItem = await toClient.CreateContentItemAsync(newContentItem);

Error below:

`Exception has occurred: CLR/System.AggregateException
An unhandled exception of type 'System.AggregateException' occurred in System.Private.CoreLib.dll: 'One or more errors occurred.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 KenticoCloud.ContentManagement.Exceptions.ContentManagementException : The specified content type does not exist.
   at KenticoCloud.ContentManagement.Modules.HttpClient.ContentManagementHttpClient.<SendAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KenticoCloud.ContentManagement.Modules.ActionInvoker.ActionInvoker.<InvokeMethodAsync>d__6`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KenticoCloud.ContentManagement.ContentManagementClient.<CreateContentItemAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at myApp.Program.<CreateContent>d__1.MoveNext() in C:\__workspace\migration\myApp\Program.cs:line 53`

**Comment by sutrkiller** [comment]
Hi, the problem is that you are trying to reference the type using codename of an item and since CM API can't find any type with such codename, it fails:
```c#
ContentItemCreateModel newContentItem = new ContentItemCreateModel
{
    Name = item.Name,
    Type = ContentTypeIdentifier.ByCodename(item.CodeName),  // on this line
};
```
Therefore, you should pass a codename of the type instead...something like: `item.Type.CodeName`.

**Comment by petrsvihlik** [comment]
I believe this is the answer:

```
ContentItemCreateModel newContentItem = new ContentItemCreateModel
{
    Name = item.Name,
    Type = ContentTypeIdentifier.ById(item.Type.Id),  
};
```

Alternatively, you can use the [delivery sdk](https://github.com/Kentico/delivery-sdk-net) (possibly with the preview api key) as the source for your import.

**Comment by petrsvihlik** [comment]
Hi @knoxor , did the advice help you? Please let us know so that we can help you resolve it asap.

**Comment by petrsvihlik** [comment]
great!
